name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/varvara-hromushina/docker-crud-app
  APP_PORT: 8041

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and test
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker run --rm \
            --network host \
            -e DATABASE_URL=postgresql+psycopg://kubsu:kubsu@127.0.0.1:5432/kubsu \
            --entrypoint pytest \
            $IMAGE_NAME:latest tests/ -v

      - name: Push to GHCR
        run: docker push $IMAGE_NAME:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop crud-app || true
            docker rm crud-app || true
            docker run -d \
              --name crud-app \
              -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} \
              --restart=always \
              ${{ env.IMAGE_NAME }}:latest
            sleep 5
            docker ps | grep crud-app
            curl -f http://localhost:${{ env.APP_PORT }}/health
